

export enum ProductType {
	DEVICE = 'DEVICE',
	SUPPLEMENT = 'SUPPLEMENT',
	SUPPORT = 'SUPPORT',
}

export enum ProductCollection {
	MASSAGER = 'MASSAGER',
	THERMOMETER = 'THERMOMETER',
	BLOOD_PRESSURE_MONITOR = 'BLOOD_PRESSURE_MONITOR',
	VITAMINS = 'VITAMINS',
	SPORT_SUPPLEMENTS = 'SPORT_SUPPLEMENTS',
	ORIENTAL_MEDICINE = 'ORIENTAL_MEDICINE',
	BANDAGES = 'BANDAGES',
	CRUTCHES = 'CRUTCHES'
}

export enum ProductStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}
